# -*- coding: utf-8 -*-
"""Lecture_210921.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1NrevDARkNMOFgdOIOp0AfTLpgEYt0Gr8
"""

import numpy as np

A = np.random.rand(4,3)
print(A.shape)
print(A)
#AxB=C C.shape? (4,2)
#B = np.random.rand(3, 2)
#print(B.shape)
#print(B)

(RaXCa)x(RbXCb) = (RcXCc)
Ra = Rc
Cb = Cc
Ca = Rb

Ca = Cc X

C = np.matmul(A,B)
print(C.shape)
print(C)

A = np.array([[7], [5]])
print(A.shape)
print(A)
# X1 -> np.matmul(X1,W) -> Yp
# data
# 1 2 3
# 4 5 6
# 7 8 9
# X1 = ? np.array
# W의 shape? np.random.rand
# Yp의 shape? np.matmul

# X1-> X2 -> X3-> Yp
# X2 = np.matmul(X1,W1)
# X3 = np.matmul(X2,W2)
# Yp = np.matmul(X3,W3)
# W1.shape?, W2.shape?, W3.shape?
# Mean 평균 squared 제곱 error/loss 계산